CREATE TABLE [Store].[Fruit]
(
	[FruitId]  INT IDENTITY NOT NULL CONSTRAINT [PK_Fruit] PRIMARY KEY CLUSTERED,
	[FirstInserted] DATETIME2 NOT NULL CONSTRAINT [DF_Fruit_FirstInserted] DEFAULT SYSUTCDATETIME(),
	[Name] VARCHAR(20) NOT NULL,
	[Colour] VARCHAR(20) NOT NULL,
	[Price] SMALLINT NOT NULL, 
    [FruitUser] VARCHAR(128) NOT NULL, 
    [FruitDate] DATETIME2 NOT NULL
)
